
###TODO===> DELETAR BD E RODAR UM PEDIDO DE VENDAS PARA VER SE OS NOVOS STATUS ESTÃO FUNCIONANDO.

###TODO=> ATRIBUIR STATUS AOS PEDIDOS DE VENDAS
###TODO=> CRIAR MÓDULO FATURAMENTO
###TODO=> CRIAR MÓDULO RECEBIMENTO
###TODO=> CRIAR DUPLICATAS CONTAS A PAGAR
###TODO=> CRIAR DUPLICATAS CONTAS A RECEBER

##FINALIZADO E TESTADO

###OK==> COMPRAS (ESTÁ ESCOLHENDO DINHEIRO COMO FORMA DE PAGAMENTO MAS PRECISA DAR A OPÇÃO PARA OUTROS)
###OK=> CADASTRAMENTO CLIENTE
###OK=> CADASTRAMENTO ENTIDADES
###ok=> CRIAR PRODUTOS
####ok=> REVISAR O MÓDULO DE VENDAS=> INCLUIR PARCELAS, INTERVALO(PRAZO),

