####TODO=> REVISAR O MÓDULO DE VENDAS=> INCLUIR PARCELAS, INTERVALO(PRAZO),
###TODO=> CRIAR MÓDULO FATURAMENTO
###TODO=> CRIAR MÓDULO RECEBIMENTO
###TODO=> CRIAR DUPLICATAS CONTAS A PAGAR
###TODO=> CRIAR DUPLICATAS CONTAS A RECEBER

##FINALIZADO E TESTADO

###OK=> CADASTRAMENTO CLIENTE
###OK=> CADASTRAMENTO ENTIDADES
###ok=> CRIAR PRODUTOS


###TODO===> FAZER O AJUSTE EM VENDAS
    ###TODO==> 1) ARRUMAR SCHEMA tbl_pedidos (INCLUIR PARCELAS E INTERVALO)
    ###TODO==> 2) ARRUMAR pedido.py => incluir PARCELAS E INTERVALO)
    ###TODO==> 3) ARRUMAR respository
    ###TODO==> 4) ARRUMAR service