class StatusCredito:
    PENDENTE = "PENDENTE"
    APROVADO = "APROVADO"
    BLOQUEADO = "BLOQUEADO"

class SituacaoEstoque:
    NAO_MOVIMENTADO = "NAO_MOVIMENTADO"
    RESERVADO = "RESERVADO"
    BAIXADO = "BAIXADO"
    ESTORNADO = "ESTORNADO"

class SituacaoLogistica:
    PENDENTE = "PENDENTE"
    EM_SEPARACAO = "EM_SEPARACAO"
    ENVIADO = "ENVIADO"
    RETIDO_FINANCEIRO = "RETIDO_FINANCEIRO"